### ISSUE TITLE
polynomial division

### ISSUE THREAD

**Issue by vtjnash** [vtjnash/Polynomial.jl#1]
implement polynomial long division
`/(num::Polynomial, den::Polynomial)`

**Comment by jwmerrill** [comment]
See also https://gist.github.com/mathpup/8514578

**Comment by vtjnash** [comment]
Yes. Just need confirmation from @mathpup that he's willing to license it to here

**Comment by jwmerrill** [comment]
@mathpup has commented on the gist to give his permission to incorporate his code into the library. You also have my permission to release my contribution under the MIT license as part of this library.

**Comment by vtjnash** [comment]
implemented in f66f7bb

**Comment by my-little-repository** [comment]
Is there a chance that this improvement could be released with the standard distribution? I am using julia 0.3 and the version Polynomial  0.0.0 from the package manager does not seem to handle division.

julia> Poly([1.0,0,0])/Poly([1.0,2,1])
ERROR: no method /(Poly{Float64}, Poly{Float64})

julia> divrem(Poly([1,0,0]),Poly([1,2,1]))
ERROR: no method div(Poly{Int64}, Poly{Int64})
 in divrem at number.jl:20

Sincerely

**Comment by mathpup** [comment]
I will defer to vtjnash on this because I am not aware of how the packaging
is done. Again, feel free to use the work I provided for division. I'm glad
it is useful.

**Comment by vtjnash** [comment]
Mostly I just forgot to call `Pkg.tag("Polynomial",:minor)`

You can also do `Pkg.checkout("Polynomial")` to jump to the HEAD of master (although reminders like this are good too)
