### ISSUE TITLE
User zero instead of convert?

### ISSUE THREAD

**Issue by andrewcooke** [vtjnash/Polynomial.jl#26]
Hi,  In your definition of eps() for non-floats, could you use zero(T) instead of convert(T,0)?  I'd like to use your module, but am not sure I want to support arbitrary conversions from integers - I do, however, have zero instances.  Thanks.

**Comment by andrewcooke** [comment]
If not I guess I can define my own eps, so it's no biggie.

**Comment by vtjnash** [comment]
Defining your own `Polynomial.eps` function is also an option, if you don't like the default option of `zero`.

**Comment by andrewcooke** [comment]
thanks!

**Comment by vtjnash** [comment]
thanks for the bug report. i had a little trouble with this too, but couldn't think of the right solution (yours) at the time

**Comment by andrewcooke** [comment]
I ended up supporting conversion (because otherwise x^2 +1 doesn't work - I am trying to simplify expression of polynomials as you described in julia-users).  But I think that if you wanted to be completely consistent then you'd also need to modify the literal integers in show() (ie replace 1 with one() etc) and even change the "2" in 2*eps(...) to be two = one(T) + one(T).

But I'm starting to think that any practical Number subtype is going to have to include convert() so I doubt this is important.
