### ISSUE TITLE
Var in type?

### ISSUE THREAD

**Issue by andrewcooke** [vtjnash/Polynomial.jl#28]
When you have binary operations on polynomials you raise an error if the variable doesn't match.  If you put the variable in the type (I just found out that types can include symbols) then you could disallow this through the type system.

So Poly would become something like `data Poly{var::Symbol, T<:Number}` and you wouldn't need the `var` attribute (or component, or whatever Julia calls these things).

**Comment by vtjnash** [comment]
this puts unnecessary work on the type system and JIT, potentially making it slower, and making the error message worse (it's called a type parameter). doing everything in meta-programming just because you can is generally not a good idea
