### ISSUE TITLE
Rename polydir to polyder

### ISSUE THREAD

**Issue by jwmerrill** [vtjnash/Polynomial.jl#9]
Matlab uses `polyder`, 'der' being the prefix of 'derivative'. Is the different spelling here intentional?

**Comment by vtjnash** [comment]
probably just an unintentional typo inherited from the original code. submit a pull request to deprecate the misspelling and I'll merge it. Also please submit a pull request against JuliaLang/ODE.jl to fix the typo there as well

**Comment by jwmerrill** [comment]
ODE doesn't appear to use `polydir`

**Comment by jwmerrill** [comment]
Catalan, DSP, and Roots are the other packages that depend on Polynomial, and none of them appear to use `polydir` either.
